add best-of-five
M4telight/pyngpong pull request #8
Opened 2017-07-30 13:56 UTC by alnkpa

2017-07-30 14:32 UTC, hrantzsch commented on game_states.py
> +    In this state, the game renders only the players' paddles for a given
state comments should not be copy pasted ;)

2017-07-30 14:32 UTC, hrantzsch commented on game_states.py
> +            uid = [p for p in self.game.players.values() if not p.is_first_player][0].player_id
extract some functions for readability

2017-07-30 18:19 UTC, Bartzi requested changes
Please change the code according to the comments ;) and we should be good to go^^

2017-07-30 18:19 UTC, Bartzi commented on game_states.py
> +        text = ':'.join(map(lambda i : str(i), self.game.scores.values()))
you can also write `map(str, self.game.scores.values())`

2017-07-30 18:19 UTC, Bartzi commented on game_states.py
> +                return
only one return after the if, is sufficient I think ;)

2017-07-31 16:05 UTC, Bartzi commented on game_states.py
> +        text = ':'.join(map(lambda i : str(i), self.game.scores.values()))
`map(str, self.game.scores.values())` is enough here ;)

2017-08-05 11:46 UTC, merged